prow-config.yaml
Use the correct branch name for the `--job-config` GitHub direct URL.
=> Fix prow-config.yaml

e2e-runner/e2e_runner/ci/capz_flannel/kube-proxy/kube-proxy-windows.yaml.j2
Reverts e2e-win/k8s-e2e-runner#37
=> Revert "Disable IPv6 feature gate"

prow/jobs/sig-windows-networking.yaml
The regex expressions were not properly interpreted when enclosed with quotes.
=> Fix tests regexes

prow/plugins.yaml
Update `config.yaml`, `plugins.yaml`, and `jobs/*.yaml` if changed on merged PRs.
=> Use 'config-updater' plugin

prow/config.yaml, prow/jobs/sig-windows-networking.yaml
Make sure we run backups for the new Prow infra as well.
=> Add kube-backup job

e2e-runner/cleanup-azure-rgs.py, prow/jobs/sig-windows-networking.yaml
Cleanup CI resource groups if the prowjob is not running anymore.
Also, add the `--dry-run` parameter (useful for debugging).
=> Improve cleanup-azure-rgs.py script

e2e-runner/e2e_runner/base.py, e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/cli/run_ci.py, e2e-runner/e2e_runner/deployer/capz/capz.py, e2e-runner/e2e_runner/deployer/capz/windows-agents.yaml.j2, e2e-runner/e2e_runner/utils.py, e2e-runner/requirements.txt
* Improve K8s agents ready wait logic
* Refactor `wait_for_agents` and `_is_k8s_node_ready` deployer functions.
* Add CAPZ `MachineHealthCheck` for Windows agents.
* Remove unused utils functions.
* Get VM route by name.
=> Improve agents ready wait & other CI updates

prow/jobs/sig-windows-networking.yaml
* Group LTSC2019 Prowjobs together
* Use consistent naming for Prowjobs
=> Use consistent naming for the Prowjobs

README.md, e2e-runner/e2e_runner/base.py, e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/cli/run_ci.py, e2e-runner/e2e_runner/constants.py, e2e-runner/e2e_runner/deployer/capz/capz.py, e2e-runner/e2e_runner/exceptions.py, e2e-runner/e2e_runner/utils.py, e2e-runner/requirements.txt
* Use tenacity for code retries.
* Updates for the `ci/capz_flannel`, `deployer/capz`, `utils` modules:
* Use tenacity for the resources wait logic.
* Tiny code optimizations.
* Remove redundant extra spaces.
=> General code cleanup

e2e-runner/e2e_runner/deployer/capz/capz.py, e2e-runner/e2e_runner/utils.py
Have the `_init_bootstrap_vm` step as part of the creation of the
bootstrap VM phase.
The `_create_bootstrap_vm` is wrapped with `retry_on_error` that will
properly cleanup the entire Azure VM in case something goes wrong
with the setup.
=> Improve bootstrap VM setup

prow/jobs/sig-windows-networking.yaml
=> Bump Azure images

e2e-runner/cleanup-azure-rgs.py
Consider the case when the prowjob doesn't exist anymore.
=> Fix cleanup-azure-rgs.py script

prow/jobs/sig-windows-networking.yaml
Add the following new jobs to Prow:
* `k8s-e2e-ltsc2022-containerd-flannel-sdnbridge-stable`
* `k8s-e2e-ltsc2022-containerd-flannel-sdnoverlay-stable`
=> Add Windows Server 2022 jobs

e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/deployer/capz/capz.py, e2e-runner/e2e_runner/utils.py
Add logs collection for the bootstrap VM
=> Collect bootstrap VM logs

e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/cli/run_ci.py, e2e-runner/e2e_runner/deployer/capz/capz.py
Make sure the bootstrap VM logs are collected at the end of the job.
=> Improve bootstrap VM logs collection

prow/jobs/sig-windows-networking.yaml
Windows Server 1909 reach end of support.
=> Remove SAC 1909 jobs

e2e-runner/e2e_runner/deployer/capz/capz.py
Rely on the `MachineHealthCheck` to delete unhealthy agents, and
only check if the agent is ready.
=> Simplify 'wait_for_agents' logic

e2e-runner/e2e_runner/deployer/capz/capz.py
Wrap the check to verify if the Azure machine is ready
with a try / except block.
=> Add try / except block

image-builder/packer/azure-cbsl-init/README.md
Document the build process with Docker `buildx`.
=> Update instructions to build container images

prow/jobs/sig-windows-networking.yaml
Bump all the other CI images to `2021.11.02`
=> Bump all CI images to `2021.11.02`

prow/jobs/sig-windows-networking.yaml
These include the latest KB update from December.
=> Update Azure images

e2e-runner/Dockerfile, e2e-runner/e2e_runner/deployer/capz/capz.py
* Bump cluster-api version
* This fixes a recent problem with `cert-manager`
* Fix python-azure-sdk errors
=> Bump cluster-api & fix python-azure-sdk errors

e2e-runner/e2e_runner/cli/run_ci.py
This can be used later on for debugging purposes.
If the RGs are not used, they will be automatically deleted by the
cronjob.
=> Retain resource group when tests failed

e2e-runner/cleanup-azure-rgs.py
This is needed to have the new functionality to have RGs retention
for debugging purposes.
=> Update Azure RGs cleanup cronjob

e2e-runner/e2e_runner/scripts/kubeadm-bootstrap.ps1
Add `--log-file` containerd service flag.
=> Use log file containerd service

prow/config.yaml, prow/jobs/sig-windows-networking.yaml
Use a separate preset with the common `focus` & `skip` regex expressions.
=> Cleanup test regex used in the job configs

prow/jobs/sig-windows-networking.yaml
This change is just cosmetic. It moves the Docker jobs to the
end of the file.
=> Re-order jobs in the config file

README.md, e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/ci/capz_flannel/flannel/windows/containerd/kube-flannel.yaml.j2, e2e-runner/e2e_runner/ci/capz_flannel/flannel/windows/docker/kube-flannel.yaml.j2, e2e-runner/e2e_runner/ci/capz_flannel/kube-proxy/windows/containerd/kube-proxy.yaml.j2, e2e-runner/e2e_runner/ci/capz_flannel/kube-proxy/windows/docker/kube-proxy.yaml.j2, e2e-runner/e2e_runner/cli/run_ci.py, prow/cronjobs/cleanup-azure-rgs.yaml, prow/cronjobs/kube-backup.yaml, prow/jobs/sig-windows-networking.yaml
Also, add `--container-image-tag` runner parameter.
=> Use ghcr.io container images

e2e-runner/e2e_runner/ci/capz_flannel/flannel/windows/containerd/kube-flannel.yaml.j2, e2e-runner/e2e_runner/ci/capz_flannel/flannel/windows/docker/kube-flannel.yaml.j2, e2e-runner/e2e_runner/ci/capz_flannel/kube-proxy/windows/containerd/kube-proxy.yaml.j2, e2e-runner/e2e_runner/ci/capz_flannel/kube-proxy/windows/docker/kube-proxy.yaml.j2, prow/cronjobs/cleanup-azure-rgs.yaml, prow/cronjobs/kube-backup.yaml, prow/jobs/sig-windows-networking.yaml
Reverts e2e-win/k8s-e2e-runner#126
=> Revert "Temporarily use fork container images"

e2e-runner/e2e_runner/deployer/capz/capz.py
Revert https://github.com/e2e-win/k8s-e2e-runner/commit/335ff5c60cb9f99466c4f58c3c41cf04315d62d6
=> Remove cluster-api azure provider pin

e2e-runner/Dockerfile, e2e-runner/cleanup-azure-rgs.py, e2e-runner/e2e_runner/base.py, e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/deployer/capz/capz.py, e2e-runner/e2e_runner/exceptions.py, e2e-runner/e2e_runner/utils.py, prow/cronjobs/kube-backup.yaml, tools/kube-backup/Dockerfile
* Fix `cleanup-azure-rgs.py` script:
* Use `total_seconds()` to determine RG age.
* Update backup secrets list.
* Set `DO-NOT-DELETE` tag:
* Otherwise, the RG will be automatically deleted.
* Code refactoring:
* Refactor the `utils.run_shell_cmd` function.
Use built-in `subprocess.run`.
* Cleanup `base.py` file.
* Cleanup e2e-runner `Dockerfile` file.
* Bump base images to `ubuntu:22:04`.
=> Code cleanup & other updates

e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/ci/capz_flannel/flannel/windows/containerd/kube-flannel.yaml.j2, e2e-runner/e2e_runner/ci/capz_flannel/flannel/windows/docker/kube-flannel.yaml.j2, e2e-runner/e2e_runner/ci/capz_flannel/kube-proxy/windows/containerd/kube-proxy.yaml.j2, e2e-runner/e2e_runner/ci/capz_flannel/kube-proxy/windows/docker/kube-proxy.yaml.j2, e2e-runner/e2e_runner/cli/run_ci.py
It allows easier testing of PRs.
=> Add param for container image registry

e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/scripts/kubeadm-bootstrap.sh
The container images when built against latest K8s code are changed.
=> Fix container images import

prow/jobs/sig-windows-networking.yaml
Fixes some tests failures for the master jobs.
=> Update repo-list URL

e2e-runner/e2e_runner/deployer/capz/capz.py
This interrogates the Azure API, and it's a good practice to
have retries here.
=> Add retries to usages list func

.github/workflows/buildx-flannel-containerd-ltsc2019.yaml, .github/workflows/buildx-flannel-containerd-ltsc2022.yaml, .github/workflows/buildx-flannel-docker-ltsc2019.yaml, .github/workflows/buildx-k8s-e2e-runner.yaml, .github/workflows/buildx-kube-proxy-containerd-ltsc2019.yaml, .github/workflows/buildx-kube-proxy-containerd-ltsc2022.yaml, .github/workflows/buildx-kube-proxy-docker-ltsc2019.yaml, .github/workflows/buildx-prow-backup.yaml, .github/workflows/prow-cronjobs.yaml, README.md, e2e-runner/e2e_runner/cli/run_ci.py, e2e-runner/entrypoint.sh, prow/cronjobs/cleanup-azure-rgs.yaml, prow/cronjobs/prow-backup.yaml, prow/jobs/sig-windows-networking.yaml
* Update default branch name to `main`
* Bump `KUBECTL_VERSION`
* Adjust the version to the K8s cluster version, that hosts the new Prow
* Update `KUBECONFIG` secret name
=> Update branch name, bump KUBECTL_VERSION & GitHub secret name

prow/cluster.yaml
Corresponds to the new Prow deployment.
=> Add Prow cluster manifest

prow/backup/backup.sh, prow/config.yaml, prow/cronjobs/prow-backup.yaml
Update configs
* Remove storage account creds from `preset-prod-azure-account`
* Re-order env vars for prow-backup cronjob container
Update backup encryption
=> Update configs & backup encryption

prow/jobs/sig-windows-networking.yaml
=> Add AKS jobs to `prow/jobs/sig-windows-networking.yaml`

e2e-runner/e2e_runner/utils/kubernetes.py
Catch all exceptions occurred during pod log stream.
=> Update `watch_pod_log` from `KubernetesClient` class

e2e-runner/e2e_runner/base.py, e2e-runner/e2e_runner/ci/aks/aks.py, e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/utils/utils.py
=> Properly set e2e tests non blocking nodes taints

e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py
Include the control-plane taints used for Docker deployments.
=> Update nodes non-blocking taints

e2e-runner/e2e_runner/base.py
The SSH private key was uploaded as a symlink since `kubectl cp` doesn't follow symlinks.
This chance adopts a workaround to avoid that.
=> Fix jumpbox pod

prow/config.yaml
=> Do not skip [Slow] tests globally

e2e-runner/e2e_runner/base.py, e2e-runner/e2e_runner/ci/aks/aks.py, e2e-runner/e2e_runner/scripts/aks/collect-logs.ps1
This could give us more information about the tests failures.
=> Collect logs from AKS Windows nodes

prow/ingress/traefik/README.md, prow/private-bins.yaml
* Add manifest with the private-bins deployment
* Update prow/ingress/traefik/README.md
=> Prow updates

prow/config.yaml
=> Increase prowjobs history

e2e-runner/e2e_runner/base.py, e2e-runner/e2e_runner/cli/run_ci.py, prow/jobs/sig-windows-networking.yaml
=> Add Ginkgo flake attempts for AKS Prowjobs

.github/workflows/buildx-flannel-containerd-ltsc2019.yaml, .github/workflows/buildx-flannel-containerd-ltsc2022.yaml, .github/workflows/buildx-k8s-e2e-runner.yaml, .github/workflows/buildx-kube-proxy-containerd-ltsc2019.yaml, .github/workflows/buildx-kube-proxy-containerd-ltsc2022.yaml, .github/workflows/buildx-prow-backup.yaml, e2e-runner/Makefile, e2e-runner/debug/setup-env.sh, e2e-runner/e2e_runner/ci/capz_flannel/cloud-init/install-golang.sh
* Fix Golang install script
* Add Makefile target to setup VSCode debug env
* Run GitHub workflows only on main branch pushes
=> Fix Flannel Prow jobs & other updates

e2e-runner/e2e_runner/scripts/kubeadm-bootstrap.ps1
Recently, in the containerd `main` branch, the following PR was merged: https://github.com/containerd/containerd/pull/8994
This makes containerd to use the new sandboxes CRI, by default.
From my observations, this is causing some issues with `kubectl exec` with Kubernetes latest `master` branch code, deployed with containerd latest `main` branch code.
Fallback to the legacy CRI implementation via `DISABLE_CRI_SANDBOXES=1`, until this issue is fixed. This will be a NOOP for stable containerd deployments.
=> Set `DISABLE_CRI_SANDBOXES=1` containerd env

prow/docs/ManualProwjobTrigger.md
=> Manual Prowjob trigger documentation
