v2/terraform_flannel.py, v2/utils.py
Make collect-log pod timeout non-fatal
Increase default pod wait time to 600s
=> collect-logs improvements

v2/ci.py, v2/civ2.py
Add ability to hold after tests have run. Useful for debugging failed tests/flakes.
=> Hold improvements

prow-config.yaml, tools/kube-backup/Dockerfile, tools/kube-backup/backup.sh
* Add logic to `tools/kube-backup` to delete older backups if `BACKUP_KEEP_DAYS` environment variable is set.
* Keep prow backups only 90 days.
=> Delete old backups

e2e-runner/Dockerfile, e2e-runner/capz_flannel.py
Additionally, unset the `KUBECTL_PATH` environment variable if
the param `--build=k8sbins` is passed, in order to use the custom
kubectl build.
=> Bundle kubectl into the runner image

e2e-runner/capz_flannel.py, e2e-runner/cluster-api/flannel/kube-flannel-windows.Dockerfile, e2e-runner/cluster-api/flannel/kube-flannel-windows.yaml.j2, e2e-runner/installPatches.ps1, e2e-runner/utils.py, image-builder/azure-cbsl-init/CustomResources/containerd/PrepareNode.ps1, image-builder/azure-cbsl-init/CustomResources/docker/PrepareNode.ps1
* Bump Flannel version to `v0.13.0-rc1`. Since commit f964a9a got merged, there is a bug with overlay networks, and pods do not have connectivity. This issue is solved with Flannel `v0.13.0-rc1`.
* Improve installPatches.ps1 script Adds support for installing `cab` packages.
* Use async cmds to install patches on all workers at once
=> Capz Flannel CI Updates

image-builder/packer/azure-cbsl-init/k8s-node-setup/common.ps1, image-builder/packer/azure-cbsl-init/k8s-node-setup/containerd/PrepareNode.ps1, image-builder/packer/azure-cbsl-init/windows-ltsc2019-containerd-variables.json, image-builder/packer/azure-cbsl-init/windows-ltsc2019-docker-variables.json, image-builder/packer/azure-cbsl-init/windows-sac1909-containerd-variables.json, image-builder/packer/azure-cbsl-init/windows-sac2004-containerd-variables.json, prow-config.yaml
* Bump CNI plugins version.
* Use global variables for the dependencies versions.
* Bump Azure Packer images to `2021-02-10` version.
=> Image builder updates

e2e-runner/e2e_runner/ci/capz_flannel/kube-proxy/kube-proxy-windows.yaml.j2
The IPv6DualStack feature was recently enabled by default on Windows.
It currently crashes the `kube-proxy` on start with:
```
F0222 server.go:490] unable to create proxier: unable to create ipv4 proxier:
Could not find host mac address for 0.0.0.0, hostname: ibflannel-m4n87, clusterCIDR : 10.244.0.0/16, nodeIP:0.0.0.0
```
=> Disable IPv6 feature gate

e2e-runner/Dockerfile, e2e-runner/cleanup-azure-rgs.py, e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/ci/capz_flannel/flannel/cni/containerd-l2bridge-windows.yaml.j2, e2e-runner/e2e_runner/ci/capz_flannel/flannel/cni/containerd-overlay-windows.yaml.j2, e2e-runner/e2e_runner/ci/capz_flannel/flannel/cni/docker-l2bridge-windows.yaml.j2, e2e-runner/e2e_runner/ci/capz_flannel/flannel/cni/docker-overlay-windows.yaml.j2, e2e-runner/e2e_runner/cli/run_ci.py, e2e-runner/e2e_runner/deployer/capz/capz.py, prow/jobs/sig-windows-networking.yaml
* Add tags to the Azure RGs.
* Cleanup the bootstrap VM early. Once the CAPZ cluster is deployed, the bootstrap VM is safe to be deleted.
* Bump `cniVersion` to `0.3.0`. Also remove the explicit DNS servers list config, since it's not required with `"capabilities": {"dns": true}`.
* Add job to cleanup orphan Azure RGs. This is meant to delete orphan CI resource groups that are left when something went wrong with the testing prowjobs. Also, fixed a small typo.
=> CI Updates

prow/cronjobs/cleanup-azure-rgs.yaml, prow/jobs/sig-windows-networking.yaml
This job is meant to run more often, and it was doing too
much noise into the Prow environment.
=> Change cleanup-azure-rgs as regular K8s cronjob

e2e-runner/cleanup-azure-rgs.py, prow/cronjobs/cleanup-azure-rgs.yaml
* Use explicit namespace when getting the `prowjob` info.
* Adjust logging messages.
* Limit cronjob history to `10`, and use `concurrencyPolicy: Forbid`
with `backoffLimit: 0` to avoid restarts if cronjob fails.
=> Fix cleanup-azure-rgs cronjob

e2e-runner/Dockerfile, e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/ci/capz_flannel/flannel/kube-flannel-windows.Dockerfile, e2e-runner/e2e_runner/ci/capz_flannel/flannel/kube-flannel-windows.yaml.j2, e2e-runner/e2e_runner/ci/capz_flannel/flannel/kube-flannel.yaml.j2, e2e-runner/e2e_runner/ci/capz_flannel/kube-proxy/kube-proxy-windows.Dockerfile, e2e-runner/e2e_runner/ci/capz_flannel/kube-proxy/kube-proxy-windows.yaml.j2, e2e-runner/e2e_runner/constants.py, e2e-runner/e2e_runner/deployer/capz/capz.py, e2e-runner/requirements.txt, image-builder/packer/azure-cbsl-init/k8s-node-setup/common.ps1, image-builder/packer/azure-cbsl-init/k8s-node-setup/containerd/PrepareNode.ps1, image-builder/packer/azure-cbsl-init/k8s-node-setup/docker/PrepareNode.ps1, image-builder/packer/azure-cbsl-init/windows.json, prow/jobs/sig-windows-networking.yaml
* Bump CAPI and CAPZ versions
* Bump wins and yq deps versions
* Fix kube-flannel Windows daemonset
Before `wins cli process run` is executed, we need the `flanneld.exe`
on the host.
* Packer: use script parameters instead of env.
Packer builds often failed because the env is not properly set.
* Fix host-gw CNI deployments.
The default Kubernetes `10.96.0.1` cluster IP doesn't work
properly with multi-nic configuration on the control-plane VM.
So, in order to have all the machines on the same L2 segment
(required for the `host-gw` deployments), we connect the K8s
agents to the same subnet as control-plane. This removes the
multi-nic workaround for the control-plane VM.
* Bump Azure images versions
=> Fix host-gw CNI deployments and other CI updates

e2e-runner/e2e_runner/cli/run_ci.py, prow/jobs/sig-windows-networking.yaml
* Use `preset-windows-private-registry-cred` for K8s `master` branch jobs.
There is a test on K8s `master` branch that uses the private registry.
* Use stable K8s version as default K8s branch param
Instead of using `master` as default value for `--k8s-branch`,
we use the stable K8s version to avoid changing the job config
every time the stable K8s version is updated.
=> Use preset-windows-private-registry-cred for master jobs

prow/jobs/sig-windows-networking.yaml
This is a follow-up PR to the upstream change from: https://github.com/kubernetes/test-infra/pull/21156
Also, disabled `[Slow]` tests as they are meant to be executed
with `[Serial]` tests (which were disabled already).
=> Update tests focus / skip regexes

e2e-runner/e2e_runner/scripts/init-bootstrap-vm.sh
A couple of recent jobs failed building Golang code with the
compiler installed from Snap store.
Use an alternate installation method.
=> Fix bootstrap VM Golang install

prow/config.yaml, prow/cronjobs/cleanup-azure-rgs.yaml
This should cover the jobs' worst execution times.
=> Decrease tests timeout to 8h

prow/jobs/sig-windows-networking.yaml
Skip the following tests with overlay job configurations:
```
Kubernetes e2e suite.[sig-node] Container Lifecycle Hook when create a pod with lifecycle hook should execute prestop http hook properly [NodeConformance] [Conformance]
Kubernetes e2e suite.[sig-node] Container Lifecycle Hook when create a pod with lifecycle hook should execute poststart http hook properly [NodeConformance] [Conformance]
```
These test cases are flaky due to a limitation of the overlay CNI
implementation on Windows.
=> Skip some container lifecycle hook http tests

prow/jobs/sig-windows-networking.yaml
Use Azure CI images from `2021.04.10` (generated with latest Windows updates)
=> Bump Azure images

prow/config.yaml
The `max_pod_age` will be used, no matter if the pod is
terminated or not.
=> Remove terminated_pod_ttl config

prow/jobs/sig-windows-networking.yaml
The `IPv6DualStack` feature gate is working with Docker and
L2Bridge deployments.
=> Enable IPv6DualStack for Docker l2bridge

e2e-runner/e2e_runner/base.py, prow/config.yaml, prow/cronjobs/cleanup-azure-rgs.yaml
* Use `6h` for Prowjobs' executions and Azure RGs age.
* Use `2h` for `kubetest` tests timeout.
=> Decrease timeouts

.gitignore, e2e-runner/Dockerfile, e2e-runner/e2e_runner/constants.py, e2e-runner/e2e_runner/deployer/capz/control-plane.yaml.j2, e2e-runner/e2e_runner/scripts/init-bootstrap-vm.sh, e2e-runner/e2e_runner/scripts/update-k8s.sh, image-builder/packer/azure-cbsl-init/README.md, image-builder/packer/azure-cbsl-init/k8s-node-setup/common.ps1, image-builder/packer/azure-cbsl-init/k8s-node-setup/containerd/PrepareNode.ps1, image-builder/packer/azure-cbsl-init/k8s-node-setup/docker/PrepareNode.ps1, image-builder/packer/azure-cbsl-init/windows.json, prow/jobs/sig-windows-networking.yaml
* Bump stable Kubernetes version to `v1.21.0`.
* Bump Golang version to `1.16.3`.
* Bump CI Azure images version to `2021.04.13`.
* Small cleanup for the Packer Windows PowerShell scripts.
* Use explicit `elevated_execute_command` for the Packer PowerShell
provisioner steps.
* Use Packer `manifest` post-processor.
=> Update CI Azure images

prow/jobs/sig-windows-networking.yaml
Add missing `--base-container-image-tag=ltsc2022` parameter.
=> Fix LTSC 2022 jobs

image-builder/packer/azure-cbsl-init/PSModules/KubernetesNodeSetup/Common.psm1, image-builder/packer/azure-cbsl-init/PSModules/KubernetesNodeSetup/cloudbase-init/cloudbase-init.conf, image-builder/packer/azure-cbsl-init/windows-ltsc2022-containerd-variables.json, prow/jobs/sig-windows-networking.yaml
* Update Azure images Packer scripts
* Bump Azure images dependencies
* `CNI_PLUGINS_VERSION` to `1.0.0`
* `CRI_CONTAINERD_VERSION` to `1.5.5`
* `CRICTL_VERSION` to `1.22.0`
* Use `2022-datacenter-core-smalldisk-g2` image for LTSC2022. This is the released Windows Server 2022 Azure image
* Bump Azure images to `2021.08.19` version
=> Update Azure images

e2e-runner/Dockerfile, e2e-runner/e2e_runner/ci/capz_flannel/flannel/kube-flannel-windows.Dockerfile, e2e-runner/e2e_runner/ci/capz_flannel/kube-proxy/kube-proxy-windows.Dockerfile, e2e-runner/e2e_runner/constants.py, e2e-runner/e2e_runner/deployer/capz/capz.py, e2e-runner/e2e_runner/deployer/capz/control-plane.yaml.j2, e2e-runner/e2e_runner/scripts/kubeadm-bootstrap.sh, image-builder/packer/azure-cbsl-init/PSModules/KubernetesNodeSetup/Common.psm1, image-builder/packer/azure-cbsl-init/PSModules/KubernetesNodeSetup/KubernetesNodeSetup.psm1, image-builder/packer/azure-cbsl-init/README.md, prow/jobs/sig-windows-networking.yaml, tools/kube-backup/Dockerfile
* Remove temporary workaround
* This was temporarily introduced with the change https://github.com/e2e-win/k8s-e2e-runner/commit/bcc8743fc842cc47aeb5c93b8c7d243cef0f5d1f
* Bump default Kubernetes version to `v1.22.1`
* Change tools/kube-backup container base image
* Use `ubuntu:20.04` instead of `ubuntu:latest`
* Bump cluster-api version to `v0.4.2`
* Use the new functionality to wait for the cluster to be ready via the flag `--wait-providers`
* Bump cluster-api-provider-azure to `v0.5.2`
* Update Kubernetes pause image
* Use `mcr.microsoft.com/oss/kubernetes/pause:3.6` container image
* Rewrite kube-proxy & flannel Dockerfiles
* The new Dockerfiles are meant to be used with `docker buildx`
* This will allow building Windows container images on a Linux machine
* Bump Azure images' …
=> Update Azure images & container images

prow/jobs/sig-windows-networking.yaml
Skip the following test:
```
[sig-windows] [Feature:Windows] SecurityContext [It] should not be able to create pods with unknown usernames
```
until the upstream issue is resolved (https://github.com/kubernetes/kubernetes/issues/104635).
=> Skip failing test until issue is resolved

e2e-runner/e2e_runner/base.py, e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/cli/run_ci.py, e2e-runner/e2e_runner/deployer/capz/capz.py
Instead of calling `_setup_infra()` in the capz `__init__`, use a dedicated method in the CI base class.
=> Add setup_infra to CI base class

e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/deployer/capz/capz.py, e2e-runner/e2e_runner/deployer/capz/windows-agents.yaml.j2
Add retry logic to re-create the Windows agents in the `e2e_runner`.
Remove Windows agents' `MachineHealthCheck` since this will not be needed anymore.
=> Improve Windows agents setup

e2e-runner/Dockerfile, e2e-runner/e2e_runner/ci/capz_flannel/kube-proxy/kube-proxy-windows.Dockerfile, e2e-runner/e2e_runner/constants.py, e2e-runner/e2e_runner/deployer/capz/capz.py, e2e-runner/e2e_runner/deployer/capz/control-plane.yaml.j2, e2e-runner/e2e_runner/scripts/init-bootstrap-vm.sh, e2e-runner/e2e_runner/scripts/kubeadm-bootstrap.sh, image-builder/packer/azure-cbsl-init/PSModules/KubernetesNodeSetup/Common.psm1, image-builder/packer/azure-cbsl-init/PSModules/KubernetesNodeSetup/KubernetesNodeSetup.psm1, image-builder/packer/azure-cbsl-init/README.md, prow/jobs/sig-windows-networking.yaml, tools/kube-backup/Dockerfile
* Log info message with Azure location used
* Bump dependencies' releases
* Bump default `kubernetes` version
* Bump `cluster-api` version
* Bump `golang` version
* Bump `containernetworking/plugins` version
* Bump Azure images to `2021.09.27`
=> Bump CI dependencies

e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/deployer/capz/capz.py, prow/jobs/sig-windows-networking.yaml
* Use 128GB for the bootstrap VM OS disk size
* Use models instead of plain dicts for network, compute, and
mgmt resources paramtereters
* Remove explicit enable of IP forwarding since this done by the
`cluster-api-provider-azure`
* Enable IPv6 for `master` branch jobs. On latest Kubernetes code,
this feature gate is locked to be enabled
=> CAPZ Deployer Updates

e2e-runner/e2e_runner/constants.py
This location sometimes has troubles spawning the Windows agents.
Temporarily disable it until a resolution is found.
=> Remove westus2 location

e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/ci/capz_flannel/kube-proxy/kube-proxy-windows.yaml.j2, e2e-runner/e2e_runner/cli/run_ci.py, e2e-runner/e2e_runner/deployer/capz/capz.py, prow/jobs/sig-windows-networking.yaml
* Remove `--enable-ipv6dualstack` parameter
* Fix l2bridge deployments
Use the same nic object when updating the VM nic ip config.
Otherwise, some NIC configs are lost (like `IPForwarding`), which is
necessary for l2bridge deployments.
=> Fix L2Bridge deployments

image-builder/packer/azure-cbsl-init/0-setup.ps1, image-builder/packer/azure-cbsl-init/windows-ltsc2019-containerd-variables.json, image-builder/packer/azure-cbsl-init/windows-ltsc2019-docker-variables.json, image-builder/packer/azure-cbsl-init/windows-ltsc2022-containerd-variables.json, image-builder/packer/azure-cbsl-init/windows-sac2004-containerd-variables.json, image-builder/packer/azure-cbsl-init/windows.json, prow/jobs/sig-windows-networking.yaml
* Add new Packer config variables:
* Add `image_version` variable, and use `latest` for all CI images.
* Add `install_latest_windows_updates` variable. Set this to `false`
for the current marketplace images since these are updated already.
* Use `20348.230.2109130355` for the LTSC2022 image
* Bump LTSC2022 CI Azure images to `2021.11.02`
=> Update LTSC2022 CI Azure images

prow/jobs/sig-windows-networking.yaml
The following test:
```
[sig-windows] [Feature:Windows] SecurityContext [It] should not be able to create pods with unknown usernames
```
was fixed into Kubernetes master.
We need this skipped into stable containerd jobs until the fix is
propagated into a stable K8s release.
=> Update `--test-skip-regex` for containerd jobs

prow/config.yaml, prow/jobs/sig-windows-networking.yaml
Without this, the `clusterctl init` command might fail with:
```
rate limit for github api has been reached.
Please wait one hour or get a personal API tokens a assign it to the GITHUB_TOKEN environment variable
```
The token used is a simple personal access token with `public_repo` access.
=> Set GITHUB_TOKEN to avoid GitHub API rate limit

e2e-runner/Dockerfile, e2e-runner/e2e_runner/ci/capz_flannel/Makefile, e2e-runner/e2e_runner/ci/capz_flannel/kube-proxy/kube-proxy-windows.Dockerfile, e2e-runner/e2e_runner/constants.py, prow/jobs/sig-windows-networking.yaml, tools/kube-backup/Dockerfile
* Disable WinDSR for WS2022 + sdnbridge.
* There's a known regression with the WinDSR and WS2022 + sdnbridge.
* Bump default Kubernetes version to `v1.23.3`
=> Temporarily disable WinDSR for WS2022 + sdnbridge and bump K8s version

e2e-runner/e2e_runner/base.py, e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/cli/run_ci.py, e2e-runner/e2e_runner/scripts/collect-logs.ps1, e2e-runner/e2e_runner/scripts/collect-logs.sh, prow/jobs/sig-windows-networking.yaml
* Add --flake-attempts parameter.
* Also, cleanup `_run_tests` function.
* Update default runner params
* Use 8 parallel test nodes, by default
* Allow 2 flake attempts for the tests, by default
* Update jobs/sig-windows-networking.yaml
* Remove explicit container command.
This was already set in the container image as `ENTRYPOINT`.
* Remove explicit `--parallel-test-nodes` param, and rely on the
default value.
* Update logs collection
* Collect Docker logs only if service is available.
* Use `tgz` logs archive on both Linux and Windows.
=> Add flake attempts runner parameter & other updates

prow/jobs/sig-windows-networking.yaml
Test containers are broken without the `command` option.
=> Fix prowjobs

e2e-runner/e2e_runner/deployer/capz/control-plane.yaml.j2
Add `MachineHealthCheck` resource for the control-plane machine.
In case of deployment failure, the control-plane machine will be
re-created.
=> Add control-plane machine health check

e2e-runner/e2e_runner/base.py, e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/cli/run_ci.py, e2e-runner/e2e_runner/deployer/capz/capz.py, e2e-runner/e2e_runner/deployer/capz/control-plane.yaml.j2, e2e-runner/e2e_runner/scripts/kubeadm-bootstrap.ps1, e2e-runner/e2e_runner/scripts/kubeadm-bootstrap.sh, e2e-runner/e2e_runner/utils.py, prow/jobs/sig-windows-networking.yaml
* Download `kube-proxy.exe` build in the userdata script
* Build conformance tests image
* Add flag to retain testing envs
* Also, retain only `master` jobs
* Use conformance image for E2E tests
* Update default `--parallel-test-nodes` param
* Match the default value given to the `--win-agents-count` param
=> Use conformance image for E2E tests & other updates

prow/config.yaml
The intent is to re-enable the tests once https://github.com/kubernetes/kubernetes/issues/107394 is fixed.
=> Temporarily skip garbage collector tests

e2e-runner/e2e_runner/ci/capz_flannel/flannel/windows/containerd/kube-flannel.yaml.j2, e2e-runner/e2e_runner/ci/capz_flannel/flannel/windows/docker/kube-flannel.yaml.j2, e2e-runner/e2e_runner/ci/capz_flannel/kube-proxy/windows/containerd/kube-proxy.yaml.j2, e2e-runner/e2e_runner/ci/capz_flannel/kube-proxy/windows/docker/kube-proxy.yaml.j2, prow/cronjobs/cleanup-azure-rgs.yaml, prow/cronjobs/kube-backup.yaml, prow/jobs/sig-windows-networking.yaml
Currently, the `e2e-win` org container images are not public yet.
=> Temporarily use fork container images

e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/cli/run_ci.py, e2e-runner/e2e_runner/deployer/capz/capz.py, e2e-runner/e2e_runner/deployer/capz/control-plane.yaml.j2, e2e-runner/e2e_runner/deployer/capz/windows-agents.yaml.j2, e2e-runner/e2e_runner/scripts/kubeadm-bootstrap.ps1, e2e-runner/e2e_runner/scripts/kubeadm-bootstrap.sh, prow/jobs/sig-windows-networking.yaml
* Update `--k8s-branch` default value.
* Update MHC resource:
* Remove `Ready: False` unhealthy condition.
* Refactor CI builds:
* Add `cri-tools` CI build.
* Build `cri-tools` and `containerd-shim-runhcs-v1` from the `containerd` source tree.
* Backup binaries before update.
* Cleanup the bootstrap VM artifacts directory.
* Don't build containerdshim separately for k8s `master` jobs:
* Rely on the containerd shim bundled with containerd build via `containerdbins`.
=> Refactor CI buils & other updates

e2e-runner/Dockerfile, e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/ci/capz_flannel/kube-proxy/windows/containerd/Dockerfile, e2e-runner/e2e_runner/ci/capz_flannel/kube-proxy/windows/docker/Dockerfile, e2e-runner/e2e_runner/constants.py, e2e-runner/e2e_runner/deployer/capz/capz.py, e2e-runner/e2e_runner/deployer/capz/control-plane.yaml.j2, e2e-runner/e2e_runner/deployer/capz/windows-agents.yaml.j2, e2e-runner/e2e_runner/scripts/kubeadm-bootstrap.ps1, prow/backup/Dockerfile, prow/jobs/sig-windows-networking.yaml
* Bump default K8s version to `v1.24.1`.
* Pin Docker jobs to K8s `v1.23.7`.
* This is the last release to support `Dockershim`.
* Use new naming scheme for CAPZ images.
=> Bump default K8s version & use new naming scheme for capz images

prow/jobs/sig-windows-networking.yaml
* Remove WinDSR disable for the LTSC 2022 sdnbridge job
* Update skipped tests from the LTSC 2022 sdnoverlay job
=> Update tests regexes

e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/deployer/capz/capz.py, e2e-runner/e2e_runner/deployer/capz/control-plane.yaml.j2, e2e-runner/e2e_runner/deployer/capz/windows-agents.yaml.j2, e2e-runner/e2e_runner/scripts/init-bootstrap-vm.sh
* Add CAPZ deployment retries:
* Retry deployments if CAPZ machines fail to provision.
* Also, remove `MachineHealthCheck` resources, since they are not reliable.
* Use Ubuntu 22.04 LTS for bootstrap VM.
=> Add deployment retries & and use Ubuntu 22.04 for bootstrap VM

e2e-runner/e2e_runner/deployer/capz/capz.py
Otherwise, the `master` jobs that build the kubelet on 22.04 LTS
will link a different glibc version than the one used by the
CAPZ Linux machines with 20.04 LTS.
=> Revert bootstrap VM to 20.04 LTS SKU

e2e-runner/e2e_runner/constants.py, e2e-runner/e2e_runner/deployer/capz/capz.py, e2e-runner/e2e_runner/utils.py
Instead of relying on `random.choice` for the Azure location selection,
we have an algorithm that determines the least used location.
This will fix some job failures related with quota limits.
=> Use least used Azure location for job runs

e2e-runner/e2e_runner/utils.py
Make sure that the utils function `sort_dict_by_value` returns an `OrderedDict`.
=> Use OrderedDict as return value

e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py
It solves some transient errors when pulling the image together with the tests cmd (we cannot add retries there).
=> Use separate SSH cmd to pull conformance image

.github/workflows/prow-cronjobs.yaml
Revert to using `KUBECONFIG_JSON`.
=> Revert `Apply Prow CronJobs` GitHub action task

e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py
This will be removed once `v1.7.0` is released.
=> Set fixed containerd version for main builds

prow/jobs/sig-windows-networking.yaml
The LTSC2019 CAPZ machines are not properly deployed with
the `v1.25.3` Azure image.
This change will be reverted once the upstream images are fixed.
=> Download K8s version for LTSC2019 jobs

e2e-runner/e2e_runner/ci/aks/aks.py
Without this, the default node RG exceeds maximum Azure RG name limit.
=> Set AKS node_resource_group

e2e-runner/e2e_runner/base.py, e2e-runner/e2e_runner/cli/run_ci.py, e2e-runner/e2e_runner/templates/conformance.yaml.j2, prow/jobs/sig-windows-networking.yaml
* Add option for pre-built K8s e2e tests binary.
* Remove --prepull-yaml option.
* Rely on the flag `prepull-images` from K8s E2E binary to cache the images before the tests.
* Unify common repo-list files.
* Reuse existing AKS+AzureCNI jobs for `1.24` release testing.
* Add AKS+AzureCNI jobs for `1.25` release testing.
=> Add Aks+AzureCNI 1.25 release testing and other updates

e2e-runner/e2e_runner/base.py, e2e-runner/e2e_runner/ci/aks/aks.py, e2e-runner/e2e_runner/cli/run_ci.py, e2e-runner/e2e_runner/exceptions.py, e2e-runner/e2e_runner/templates/jumpbox.yaml, e2e-runner/e2e_runner/utils/kubernetes.py, e2e-runner/e2e_runner/utils/utils.py, prow/jobs/sig-windows-networking.yaml
* Add option to install private binaries:
* The private bins should be given as a URL to a zip archive, which
should contain everything necessary to be installed
* Use private binaries for AKS 1.24 + WS 2019 job:
* Install the private binaries required to enable proxy terminating
endpoints feature gate on WS 2019 with AKS 1.24.
=> Add option to install private binaries & use them for AKS 1.24 + WS 2019

prow/config.yaml, prow/jobs/sig-windows-networking.yaml
Update E2E tests
* Update global `TEST_SKIP_REGEX`:
* Do not skip `[Slow]` tests globally.
* Remove excluded `HostProcess` tests since they are fixed now.
* Use a patched `e2e.test` binary that includes new `[sig-network].LoadBalancers`
tests back-ported to `v1.24.6`. The new tests are marked as `[Slow]`,
so we don't use this tag for `--test-skip-regex` parameter.
=> Update E2E tests

prow/config.yaml, prow/jobs/sig-windows-networking.yaml
* Update `TEST_FOCUS_REGEX`
* Use the same test focus regex as the upstream capz e2e tests
* Decrease frequency of Flannel jobs
* Run Flannel with Docker runtime jobs every 3 days
* Run Flannel with containerd runtime every 2 days
=> Update job configs

prow/jobs/sig-windows-networking.yaml
Version 1.25.2 is not supported anymore in some of the Azure regions.
=> Update AKS 1.25 version

.github/workflows/docker-buildx.yaml
Copy manifest from base image only if built image has manifest list.
=> Fix flannel daemonset container images

e2e-runner/e2e_runner/base.py, e2e-runner/e2e_runner/cli/run_ci.py, e2e-runner/e2e_runner/exceptions.py, prow/jobs/sig-windows-networking.yaml
* Fix no-color ginkgo flag, This didn't appear for conformance images >= `v1.27`
* Add `--conformance-image` option. Allow customization of the conformance image to be used when running E2E tests.
* Remove explicit entrypoint override. This is not needed, since that's the default Docker image entrypoint.
* Add AKS 1.26 with AzureCNI testing.
=> Add AKS 1.26 + AzureCNI testing and conformance tests updates

prow/jobs/sig-windows-networking.yaml
Reverts commit https://github.com/e2e-win/k8s-e2e-runner/commit/fc50b113af1ac8ed11c03779de214c27de09cd73.
=> Explicit `command` is required for ProwJobs

.vscode/tasks.json, e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py
* Local debugging update:
* Set `PYDEVD_WARN_EVALUATION_TIMEOUT` env variable.
* Add retries when building CI binaries
=> Fix CI builds flakiness

e2e-runner/e2e_runner/cli/run_ci.py
Multiple E2E tests fail due to lack of resources on the Windows agents.
=> Bump Windows agents size to `Standard_D4s_v3`

prow/jobs/sig-windows-networking.yaml
Use the service name instead of hard-coded pod IP.
=> Fix the private binaries endpoint

prow/config.yaml
Use 'h' unit since 'd' is not valid.
=> Fix Prow config

e2e-runner/e2e_runner/ci/aks/aks.py
This help displaying the tested AKS version in the testgrid results.
=> Create metadata artifact in the AKS CI/CD jobs

e2e-runner/e2e_runner/base.py, e2e-runner/e2e_runner/utils/kubernetes.py, e2e-runner/e2e_runner/utils/utils.py
The logs watch is not stable for long running pods, since the `kubectl` connection drops sometimes making the jobs flaky.
We don't really need to watch the logs during the tests, so we can just get the logs when the tests finish.
=> Get the pod logs when tests finish

prow/config.yaml, prow/jobs/sig-windows-networking.yaml
Only run these tests on the following Prowjobs:
- AKS 1.24 with Windows Server 2022
- AKS 1.25 with Windows Server 2019
- AKS 1.25 with Windows Server 2022
- AKS 1.26 with Windows Server 2019
- AKS 1.26 with Windows Server 2022
The only missing AKS testing configuration is 1.24 with Windows Server
2019. Currently, the new tests flake a lot on this deployment. The tests will be enabled here as well, after the flakiness is resolved.
=> Restrict `[sig-network]` Networking Granular Checks

e2e-runner/e2e_runner/ci/aks/aks.py, e2e-runner/e2e_runner/cli/run_ci.py, e2e-runner/e2e_runner/scripts/aks/enable-proxy-terminating-endpoints-feature.ps1, prow/docs/AksTestCases.md, prow/jobs/sig-windows-networking.yaml
* Fix `_get_latest_aks_patch` function:
* The function was not returning the latest patch version for the specified release.
* Remove private HNS patch since this is GA now:
* Also, explicitly enable `ProxyTerminatingEndpoints` feature gate on AKS clusters that are below 1.26 release.
* Use patched `e2e.test` binary for all the AKS Prowjobs:
* The patched E2E binaries contain the submitted test for `ProxyTerminatingEndpoints` feature gate, and other fixes that are not yet backported.
=> Aks CI/CD updates

e2e-runner/e2e_runner/base.py
As part of the AKS e2e tests, we are running tests marked as `[Slow]`,
so we need to increase the ginkgo timeout (defaults to `1h`).
=> Use `3h` ginkgo timeout

prow/jobs/sig-windows-networking.yaml
Kubernetes 1.25 or newer E2E tests use Ginkgo v2. This version doesn't properly include the flake tests in the junit report.
Therefore, the testgrid dashboard loses the visibility of the flake tests. It will render the flake tests with green color, similar with the tests that didn't flake at all.
=> Remove `--flake-attempts` parameter

prow/config.yaml
Simplify the regex for the tests to run only Windows related tests, and Conformance / NodeConformance.
=> Update global regex for tests

e2e-runner/debug/parse-prow-config.py, prow/config.yaml, prow/jobs/sig-windows-networking.yaml
Add separate tests regex preset for AKS tests, and re-use the old one for the Flannel tests.
Additionally, skip `[sig-api-machinery]` and `[sig-cli]` tests for AKS with AzureCNI testing.
=> Use separate Prow tests regex presets

prow/config.yaml
These are not networking-related tests, and some of them flake with:
```
net/http: TLS handshake timeout
```
on the `kubectl` side.
=> Skip `[sig-auth]` tests on AKS

prow/jobs/sig-windows-networking.yaml
Experiment with running AKS tests with less parallel test runners to see if it helps with the flakiness of the tests.
=> Use `--parallel-test-nodes=2` for AKS Prowjobs

prow/config.yaml, prow/jobs/sig-windows-networking.yaml
* Experiment with running E2E serially to see if it helps with tests flakiness
* Skip `[Slow]` tests that are not `[sig-network]`
=> Update AKS ProwJobs

e2e-runner/e2e_runner/base.py
* Update ginkgo flags used for the E2E tests:
* Kubernetes v1.24 reached end of life, so we can safely assume that all
tested clusters will be v1.25 or above.
* Remove `show-node-events` ginkgo flag:
* This flag causes a lot of spam in the logs, and it's not that useful.
=> Update E2E ginkgo flags

e2e-runner/Dockerfile, e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/ci/capz_flannel/flannel/windows/containerd/kube-flannel.yaml.j2, e2e-runner/e2e_runner/ci/capz_flannel/kube-proxy/windows/containerd/kube-proxy.yaml.j2, e2e-runner/e2e_runner/cli/run_ci.py, e2e-runner/e2e_runner/constants.py, e2e-runner/e2e_runner/templates/capz/cluster.yaml.j2, e2e-runner/e2e_runner/templates/capz/control-plane.yaml.j2, e2e-runner/e2e_runner/templates/capz/windows-agents.yaml.j2
* Remove `--container-runtime` e2e-runner flag, since containerd is the only tested continer runtime.
* Use external Azure cloud provider for kubelet. The cloud provider is installed via Helm.
=> Update `capz_flannel` CI

e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/constants.py, e2e-runner/e2e_runner/utils/utils.py
We need to explicitly set the Azure cloud-provider image tag when deploying Kubernetes latest `master` branch code.
=> Fix Flannel Kubernets `master` Prowjobs

e2e-runner/Dockerfile, e2e-runner/e2e_runner/ci/capz_flannel/bootstrap_vm.py, e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/ci/capz_flannel/cloud-init/install-kind.sh, e2e-runner/e2e_runner/ci/capz_flannel/cloud-init/userdata, e2e-runner/e2e_runner/scripts/kubeadm-bootstrap.ps1
* Remove cri-tools installation from Windows nodes:
* This is not needed for normal operation of Kubernetes Windows agents.
* Bump kind to `v0.20.0`
* Bump bootstrap VM to Ubuntu 22.04
* Bump default Kubernetes version to `v1.28.1` for `capz_flannel` CI
* Bump `CAPI_VERSION` to `v1.5.2`
=> Update capz flannel CI dependencies

e2e-runner/e2e_runner/scripts/kubeadm-bootstrap.ps1, prow/jobs/sig-windows-networking.yaml
* Do not set `DISABLE_CRI_SANDBOXES`:
* This doesn't work anymore, since the CRI legacy implementation is removed now.
* Do not build latest `main` containerd:
* There is a known regression with latest containerd and sandboxed CRI. Re-enable containerd builds once the issue is fixed https://github.com/containerd/containerd/issues/9037.
=> Fix Kubernetes `master` Prowjobs

.vscode/launch.json, e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/cli/run_ci.py, e2e-runner/e2e_runner/constants.py, prow/jobs/sig-windows-networking.yaml
- Update bootstrap VM size to `Standard_D8s_v3`.
- Update Prowjobs presets.
- Use azure cloud provider helm repo from stable branch.
- Use LTSC 2022 for Kubernetes master branch Prowjobs:
- Also, update `--win-os` parameter default value to `ltsc2022`.
=> Update Kubernetes master branch Prowjobs

.github/workflows/prow-cronjobs.yaml, prow/Makefile, prow/backup/Dockerfile, prow/cluster.yaml, prow/config.yaml, prow/docs/ProwAksUpgrade.md
* Bump `KUBECTL_VERSION` to match the Prow AKS cluster.
* Update `prow/Makefile`:
* Use `kubectl replace configmap` for all the make targets that update configmaps.
* Upgrade Prow components:
* Bump Prow image tags to `v20231130-2f95ffc454`.
* Add `prow/docs/ProwAksUpgrade.md` documentation.
=> Prow Cluster Updates

prow/docs/E2ETestRegex.md
Document the E2E Test Regex used by the CAPZ Flannel & AKS CI's.
=> Add `prow/docs/E2ETestRegex.md`

e2e-runner/e2e_runner/templates/capz/control-plane.yaml.j2, e2e-runner/e2e_runner/templates/capz/windows-agents.yaml.j2
Following removal of in tree cloud provider code, azure-container-registry-config is deprecated: https://github.com/kubernetes-sigs/windows-testing/pull/420
=> Remove deprecated azure container registry config flag

e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py
Fix for ltsc2022 E2E runner failures on kube proxy version mismatch  for sdnbridge and sdnoverlay master branches as a result of this  PR: https://github.com/kubernetes/kubernetes/commit/98c29f0312190904f55d62a4b4820fc17119ec10
Failure log:
File "/usr/local/lib/python3.10/dist-packages/e2e_runner/ci/capz_flannel/capz_flannel.py", line 457, in _setup_capz_cluster
self._validate_k8s_api_versions()
File "/usr/local/lib/python3.10/dist-packages/e2e_runner/ci/capz_flannel/capz_flannel.py", line 847, in _validate_k8s_api_versions
raise e2e_exceptions.VersionMismatch(
e2e_runner.exceptions.VersionMismatch: Wrong kube-proxy version on node capzctrd-1715925611-control-plane-qctvr. Expected v1.31.0-alpha.0.803+5ceb99dc6bae8a, but found
=> Deprecate Node Kube Proxy Version check 

e2e-runner/e2e_runner/ci/capz_flannel/kube-proxy/kube-proxy-windows-hpc/cmd/init/main.go, e2e-runner/e2e_runner/ci/capz_flannel/kube-proxy/kube-proxy-windows-hpc/kube_proxy/types.go
This PR updates the add command result parser to match the spec in: https://github.com/containernetworking/cni/blob/v1.0.0/SPEC.md#section-5-result-types
=> Update sourcevip result parser

.vscode/launch.json, e2e-runner/Dockerfile, e2e-runner/e2e_runner/ci/capz_flannel/capz_flannel.py, e2e-runner/e2e_runner/cli/run_ci.py, e2e-runner/e2e_runner/constants.py, e2e-runner/e2e_runner/templates/capz/control-plane.yaml.j2, e2e-runner/e2e_runner/templates/capz/windows-agents.yaml.j2, prow/jobs/sig-windows-networking.yaml
- add Server 2025 tests
- use ubuntu 2404 from community gallery
- update versioning logic to match community gallery versions
- limit regions to north central us for availability of images
=> Add Server 2025 Tests

e2e-runner/Dockerfile
Hitting this error remotely that isn't occurring locally when I build the image
```
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you have pipx installed.
See /usr/share/doc/python3.12/README.venv for more information.
note: If you believe this is a mistake, please contact your …
```
=> temp: revert ubuntu 24.04 upgrade to investigate pip install break

e2e-runner/e2e_runner/templates/capz/control-plane.yaml.j2
This PR:
- removes the deprecated kube-apiserver cloud-provider arg which was deprecated in [release 1.29](https://github.com/kubernetes/kubernetes/blob/f0077a3689669018557de723a0416fda267d132f/CHANGELOG/CHANGELOG-1.29.md#:~:text=%40sttts\)-,Deprecated%20the%20%2D%2Dcloud%2Dprovider%20and%20%2D%2Dcloud%2Dconfig%20CLI%20parameters%20in%20kube%2Dapiserver.%20These%20parameters%20will%20be%20removed%20in%20a%20future%20release.%20\(%23120903%2C%20%40dims\)%20%5BSIG%20API%20Machinery%5D,-Dynamic%20resource%20allocation)
- it has been removed in release 1.33 through this [PR](https://github.com/kubernetes/kubernetes/pull/130162)
=> remove deprecated kube-apiserver cloud-provider arg
